# -*- coding: utf-8 -*-
"""Pyspark With Python-GroupBy And Aggregate Functions 5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r4V-B5ibmQ51LJGZDMUuualeV235dFx4

### Pyspark GroupBy And Aggregate Functions
"""

!pip install pyspark

import pyspark

from pyspark.sql import SparkSession

spark=SparkSession.builder.appName('Agg').getOrCreate()

spark

df_pyspark=spark.read.csv('test3.csv',header=True,inferSchema=True)

df_pyspark.show()



df_pyspark.printSchema()

df_pyspark.groupBy('Name').sum()

## Groupby
### Grouped to find the maximum salary
df_pyspark.groupBy('Name').sum().show()

df_pyspark.groupBy('Name').avg().show()

### Groupby Departmernts  which gives maximum salary
df_pyspark.groupBy('Departments').sum().show()

df_pyspark.groupBy('Departments').mean().show()

df_pyspark.groupBy('Departments').count().show()

df_pyspark.agg({'Salary':'sum'}).show()













