# -*- coding: utf-8 -*-
"""pyspark_introduction.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C_-aAJ9BnRl9d3cm371aIctnaePQT3v0
"""

!pip install pyspark

import pyspark

import pandas as pd
df=pd.read_csv('test1.csv')
df.head()

from pyspark.sql import SparkSession

spark=SparkSession.builder.appName('Practise').getOrCreate()

spark

df_pyspark=spark.read.csv('test1.csv')

df_pyspark

df_pyspark.show()

df_pyspark=spark.read.option('header','true').csv('test1.csv')
df_pyspark.show()

type(df_pyspark)

df_pyspark.head(3)

df_pyspark.printSchema()

